window.OCR_DATA = {
  "page-001": {
    "file": "page-001-induction-fort-macarthur.jpeg",
    "text": "My WORLd WAR II SERVICE IN the ARmy\nI wAs INDucted into The ARmy, the\nIth of OctobER 1943 IN Los AngeLes, CA.\nI RepoRted to FuRt mAcARthur on the\n23ed of OctobeR 1943, we WeRe airen\na quick Rundown of Army Routine\nAnd Issued our urforms, given short\nHaircuts, SeveRAL Shots weRe AdmInIst-\nEREd. Some Recruits passed out wien\nThey SAW The NeedLe, of CouRse TheRe\nWeRe Stories diedulated AbouT big\nSqUARE KoedLes. I CANt ReCALL WhAT\nShots they were, but ouR ARms WeRe\nquite SwoLLen FOR SeVeRAL DAYS,\nthey gAVe US A pRe-VIew of gettIng\nup quickly in The eARLy morning, by\nblowing & Enqie, on WeRe to be\nOutside information in 10 minutes.\nYouR Name wAs CaLLed And you AnSWeR.\ned present And Accounted FoR.\nThe Sargent, Asked Those in Line, who\nwould be interested in PoLIce WORK\ntake / step FoReWARd. Onite a few"
  },
  "page-002": {
    "file": "page-002-basic-training-camp-barkeley.jpeg",
    "text": "thinking that That would be a good 3.\nThing to de in the sargent then said\ntreks Line up foR bReAkfAst\nAnd The PoLice Volunteens woald\nPoLice the AREA. AfteR they finished\ntheylankd go to breakfAst, It wAs\nA LessoN Not to roLunteeR if you\ntart know what you were do unteerig foR.\nAfter About AWEEk, we were\nLoaded on A tRAin togoto bASIC\nwe went NoRth foR AwhiLe, then we\nwent oveR the SIeRRA Neved+ Mts\nIt WAs A beAutifuL RidegAFteR a\nTwo day Ride We disembARked AX\nADeLine Texas, We WeRe tAken by TRucks\nTo A CAmp LaLked, CAMp BARkLeY.\nAs We ARRired we Looked At ouR Nest\nHomes, They WeRe TAR PAPER BARRACKS\nThe flooRs weRe PLAnKS And hAd CRACKS\nbetween the BoARds. We weRtoLd\nthat these BARRACKs WeRe to be CLeAn"
  },
  "page-003": {
    "file": "page-003-live-fire-basic-training.jpeg",
    "text": "3\nAT ALL Fimes, Not Knownry TexAs\nNeatheR, It diant sound too hARd\nto do. They showed us how the ARmy\nwanted us to Keep our footlockeRs,\nFoothockeRs ARe Where you Keep Your undeR-\nWeAR, YouR sockS, ShAVInG GeAR, And ALL\nYouR personal Effects, Your Shoes were\nto shine hike A New penney. The BARRACk\nWeRe to be Kept so CheAr that if the\nCApTAIn inspected, And in wiping with\nWhite Gloves got them dirTy the Whole\nPlAtooN would be RestRicted And\nNo weekend passes wouLd beIssued.\nNo one wanted to be quiLty efrestri\nTIng ALL, TheRe WAS ALOt of SONA 4\nwateR used foR GIing the BAFRACKS\nAFTeR CleAning then you hoped thAt\nthe wind wonhdnt Blow, As the SAnd\nwould blow up than the CRAcks In\nthe fLook, The mspection would\nhAppen AfteR BReAKFAst. They hAve\nA SAyma In texas, it you dont Like\nthe WeAtheR WAIt 5 minutes And it will\nchange, ThIs WAS SO TRne"
  },
  "page-004": {
    "file": "page-004-medical-training-oreilly.jpeg",
    "text": "BASIC TRAINing hAsted foR\n4\n12 WeeKs. We had quite ALot of\nLASS WORK- LeARNiNG MAP ReAdING\nCOMPASS TRAInIng, ARmy EMIgniTe es\nSIR - NO SIR pROPeR WAy to SAhnte A\nSupeRIOR, BASiC FIRst Aid eta, We\nWere Assiqned Spearfic ChoRes, WORK-\nIng K.P, GuARd Duty, ALso We dAILy\ndid CALASeniCS - We MAde MARcheS With\nfuLL BACK PACKS. We CARRIEd hALF A\nTent in ouR BACK PAck And AtNight\nYou pitched tent with AnotheR fellow, And\nYou BetteR hAVe YouR tent hALves, We\nALso did Night PRothems NheRe you\nwould be in a trench And you had to\ncome out s The tRênch And cReep\nAnd CRAwL acRoss AfieLd And they\nWound fire hive Ammunitor orek the\ntopot you, you Learned sooN how to\nKeep down. It wAS A RAIney Night\nwhen we did this, the trench had\nAbout Afoot of wAteR In it. so it\nWAS ReAL mesSy tO CReeP& CRAWL,\nThere wAS A YouNg fellow Who SAId"
  },
  "page-005": {
    "file": "page-005-camp-beale-camp-gruber.jpeg",
    "text": "*= CouLdn't do this. Hewastold\nHE HALto do It So get withit, Well\nhe no more than Got out of the\nTRench And He HAd A ERELECtIC FIt.\ntheynan te stop the Guns and get A\nLiHER & CARRIed NIm Cif The RANGE,\nWe hereR sAW hIm AGAin So I GuesS\nHe Received A MedICAL DISChARGe,\nWe had to TAKe A EGLIVİL ALiY\nTest so they ConLe ReAssign you\nto OfficeRs TRAining OR A medIcAL\nTRAining At AlARMy HOSpITAL, I\nSCORed 115 PoInts And WAs given a\nChoice of doing Either tRAining, I WAS\nPeting A LittLe ARmy smARt And choose\nThe MedICAL TRAMInG, WhILE iN BASK\nTRAIninG I tooK up SmoKig AS BAck\nhouR they would taKe A fire minute\nbReAk And they would SAy \"AH Light\nup that wants to, I thought why\nNot Join with eveRyone Asthey ALL\nSeema to enjay the bRenk. This bad\nWAbit hasted Aboat 45 yeARs AHL\nbecame so veRy hARd to Stop."
  },
  "page-006": {
    "file": "page-006-unit-formation-blindfold-test.jpeg",
    "text": "Finally the day arrived and a was\ncalled to go to spring field mo. L\n• Redly Deseral Naspital, We were assigned\nto nice white Barracks there. So mach\nnicer than The tar Paper ones in\nCamp Barkly. We were Told that\nWe wane go to Classes, and also\nwork in the Wards at the Hospitas\ndich good in all The classes ex\nCeph in materia medica. This was\nin the use of math maties, where you\nhad to know aboat grams, and ales\nproblems that you hecked a chemistry\nbackground. + never took Chemistry\nin kanh school, twas suptonall\ngood ar mandageng\nand aten tic\nClara graduated and was to he\nassigned as a Unit, t and another\nfellow chanh get assigned, as\nthey wantue us to stay a little\nlonger and + was to teach field.\nbandagig & cant remember what\nPail Wilhe was to teach."
  },
  "page-007": {
    "file": "page-007-motor-pool-transfer.jpeg",
    "text": "I stayed at O Rielly another I\nmonth, and a half. Then a was\nsonh back to Barkly for reassgh.\nment, + was then reunited with\na fellow fian san Diego His name\nwas sweeney, the Had been a\nPharmitical Salesman in Civilian\nlife ta basie Training he had\nsupered a groin rupture, and was\nfuss reconoring as d returned to\nBarkly. I was soon on anathel\nRevie West, I wen on my\nway To camp Beale in Callarnin.\nIt was locatul near marisal Ca.\nThis was what they called a 00 witch\nmeant yor unre going over seas.\nafter a short time there aren-\nments were being nade, Theiler\n99 al us as a naih and siterd\nOf going orker sear, Ne were te hen\nback to camp Aruber en\nOKlahoma to form a Frill Enac-\nmation limpital. We again had t"
  },
  "page-008": {
    "file": "page-008-convoy-departure-new-york.jpeg",
    "text": "attand more classes and become\na cohecine unit, We became the\n135th Evacuation Hospital. The\nCadre in our unit was a bunch\nof infantry rejects they au has\nstripes on thett unforms, afte\nall the trauma some of us had\nranks, and earm more pan. The\nworsh part was they were s\ndo all the teaching. I kell aslee\nin a class on bandaging and the\nargent had a felton test torne\nvake sue up, le said denipose\nyou know all cent this anklect\nlast bandage blind freded, Wett\nThat he hat one come up front\nblind told me nud said go ahead,\ni dio the brand age and after clam\nI ran to heat him to the captains.\noffice. The first Sargent washt"
  },
  "page-009": {
    "file": "page-009-convoy-collision-at-sea.jpeg",
    "text": "on to let a to the\nLaptain, as he wao a frind of tho\nfellow teaching the Class. Well in\nthe meantime the class instructe\nCome in, and there wis some lond\nepclaisations made, The captain\ncame to the door to see what\nwas happening. He told the first\nsurgent to core down, and he\nasked me to come suto his office.\n- enflained estat tuppened and\nI told chin t wond like a transfer\nto another Unit, He said te couldn't\ndo that bat a coned transfer to The\nmator Pool of + wantic, and 1 wouldnt\nhave to attend any man senses.\nliked Savent ducia who run\nthe mater Gool, He made she\nthe Moler Pool dispatcher, soow\nafter we were on the train\nand we found our destination"
  },
  "page-010": {
    "file": "page-010-england-france-germany-advance.jpeg",
    "text": "Is he Fart Dix Tear new Brun-\nswick, new Jersey, aptr a conple\nof dark there we were taken to\nnews 2alk, and boarded a ship header\nfer Eurape. We chanh know it brit\nwe were in a 99 boat convoy\nheaded for France. Finally goung\nto the War zone, We departed Men\nJuR the 23rd of march. Vt was\ninteresting lookig either directión\ntRee boats, all in a row, as far,\nas you could sue. Each day ne\npractised drills, in care their words\nbe an emergency we were to come\nto the deck for struction, the\nship was 3 halls deep in the vessel.\nhany people on the boat were\nsen sick It was eatreated by\nsick Bay ahonk 60% i perconel\nwere up chuching,\nOn about the 5th right around\n10 pm a was layme on zey tunk\nunen more was a grame sound"
  },
  "page-011": {
    "file": "page-011-hamborn-motor-pool-barters.jpeg",
    "text": "and the boat kind of lurched, I\nIt sounded, + thought like mee\nhad strick a sand bar and it\nwas moving back & forth trying\nti dislodge itself, then the\nemergency bella y lighto come\nOn and we were to go to the\nAce, several fellows completly\nlet it. a beg fellow firm oKlahom\ncame running, andplailma his arms\nHe ran curer quite a fou- perple\nand really messed up the evacuatin\ndrill, I and a pelow named Bear\nRecited there was no way to trus\nto get out, and that ave world\njust wait, and go bet uten tingo\nGreets don. What happened was\nLat a torpedo, but the night was\nLet feel end a eat apral\nand turned, and came right\nin freset of us. We hit there\nright in the middle of there boat"
  },
  "page-012": {
    "file": "page-012-paris-supply-run.jpeg",
    "text": "It hit them right in The Carr\n12\nQuartes. We heard it Kited seven\nof their can. The scrapmy soun\nwe heard was our boat a brym\nIs dislodge from Them, Theirdargo\nwas Iti Octane basoline. yur\nhad hit them 10 Tether wan\nWe all world have been blown\neat of the water. The Left mornin\nthe castain said me cult 9000\nin the energency drill that me\nwondert hame to practise anymore,\n1 Laured the drel wras a complete\nflap, and that we were so fortunate\nthe alive. Our chip was to go to\nSouth HAmpton England for repairs. We\narried in So. Hampton april 6 and was\ntransferred to an English Limy lost\nto go across the, Englesh Channe to\nFrance. We landed on the coush hear\nnormandy beach. We was assigned\n* Camp Lucky Trike, a tent camp:\nNear Rouen Frence. We sever got."
  },
  "page-013": {
    "file": "page-013-lyon-eisenhower-jacket.jpeg",
    "text": "our Tents pat us than we were toed\nto pack up, and that we were how\nin the Second army and that we\nwire going I Catch up to Pettons\nArmy, on his drive there France, anh\ninto Germany, We wenk thre\nthe magenat line, and into Dermany\nthru lacher, The city of hachen\nwas a completely bombed out pace.\n+ dra't beleine that a snigle belani\ndown town hed 4 outside walls stand-\ning. We hurriss thra as me were\ntrying I catch Patten, We passed a\nOnlu to see in compietly devestates.\nat tir point we receined, arders\nand net up our Haspeted there. We\narrived there, and trok over their\nKospital aad all of the houses adjacen\nTh the has pitas to horse orr troops.\nThe motor Pook took over a large"
  },
  "page-014": {
    "file": "page-014-marseille-redeployment.jpeg",
    "text": "garage ass nad a lot a room far\n14\nour Vehicles. We all learned a fun\nwords in Herman, We would spehange\nSchrap a son the Whit bin.\nWe also were able to trade fm thras\nbike Cameras, Bissenlars ete,\nwhile in Hambourne the supply\ndeitenant, Ih entrader was gring\nto snake a trip to several Supply\nRepate. Being & was the Motor Pool\ndisfatcher & chose to dreir him. a\nSargent, prose the supply ooin sias\n, Our first 2 too was\nin Paris. We visited a wine Cellar\nunder the street. The wine bottles\nwere stored on shelves that could\nthe rotated. It took year for the\nwine to complete the circle in the\nageing process. after touring the\nwine cellar we came up into a large\nfores and they had ma sample the\nurne. It was i whete or clear as water"
  },
  "page-015": {
    "file": "page-015-north-atlantic-storm.jpeg",
    "text": "and was very good, after Leaving 15\nParis ur went forth to 2ios. st\nwas a heantune City, We went to a\nsupply depot several miles out in\nthe country, at. Intrater got both\nSarpent Balden, and myself a\nEisenhower Jacket. To matre a long\nStory short, We tad a lot of four\nand He trip took I/ days,..\ngo where the 2t. had business.\nWhen we got back to Hambourne\nthe war in Surape was comme\nto a close. Shortly after un was\nordered ti go to a comp near\nmarseille, It wan ances a RaR\nCamp, and was in the desert, RAR.\nmeand Rest + Recuperanon. treatly\nThink they wanted us Clot a\nport so we could he sent to the\nPacifie area. Apta several weaks\nwe recuied orders to load ou\na ship going to the Orient fr\noccupation duty."
  },
  "page-016": {
    "file": "page-016-fort-dix-homecoming.jpeg",
    "text": "ax armistice brought the war in!\nEurope to the end. now the\nproblem was to bring our serocce\nmen home to he discharged, a point\nsystena was devised to sanh the\nmen who had been in the European\nares the longest to he fish to\ngo home.\nto happened that we had\nbeen first loaded in our boat. Then\nit was decided to load the habet\nit was decided to load the highet\npoint men on our boat and to\nsend thứ boat to the 2.5.Q, They\ndecided to leave us as they disch\nwant to unload our equipment.\nWe Left France on the 17th af ang-\nust and for some reason after\nleaving the meditranium we went\nhate to cront that e reint\na big storm and t jush want tosay\nA never deleived waves coned be si\nlarge, Im sure that waves were\n50 mr more fut in heiqut. We were"
  },
  "page-017": {
    "file": "page-017-discharge-fort-macarthur.jpeg",
    "text": "tossed aboat like a les be-\n11\nthose huge wares, Wel were told\nto say below but, → quot had II\nhave a look. One look is all\nWanted tie never forget that suan.\nWe arrived in he 20rk on any\n27. 1945, again ave were sent\nto Fort Dix in New Jersey, We\nspent some time there and finally\nput on a train to go ts California\nsee than to a po\nspent y days\nU.SA, We arrened at Fort inc.\nCerthur 28 Feb 1446, after a perio\nof time I was discharged on raick\n31, 1944. iny total service time\nwas 2 years, 3 nos, and 28 days\nI recover 4 medals and alat of\nvaluable experience as a soldier."
  }
};
