window.STORY_DATA = {
  acts: {
    training: {
      label: "Act I",
      title: "Training the Medic",
      summary: "From induction in Los Angeles through the long apprenticeship that turned a draftee into a field hospital soldier."
    },
    crossing: {
      label: "Act II",
      title: "Crossing the Atlantic",
      summary: "The unit stages in New Jersey, boards a convoy, and reaches Europe only after a frightening collision at sea."
    },
    europe: {
      label: "Act III",
      title: "Europe in Motion",
      summary: "The 135th Evacuation Hospital races through France into Germany, settles into occupation duty, and briefly sees a different side of the war."
    },
    return: {
      label: "Act IV",
      title: "The Return Home",
      summary: "Redeployment orders, a brutal Atlantic crossing, and the slow trip back to California close the wartime journey."
    }
  },
  documents: [
    {
      id: "page-001",
      legacyId: "IMG_0524",
      pageNumber: 1,
      file: "imgs/page-001-induction-fort-macarthur.jpeg",
      title: "Induction at Fort MacArthur",
      summary: "The opening scan covers induction in Los Angeles, uniforms, shots, and the setup to the 'police work' lesson.",
      transcription: `I was inducted into the Army the 7th of October 1943 in Los Angeles, CA. I reported to Fort MacArthur on the 23rd of October 1943. We were given a quick rundown of Army routine and issued our uniforms, given short haircuts, and several shots were administered. Some recruits passed out when they saw the needle. Of course, there were stories circulated about big square needles. I can't recall what shots they were, but our arms were quite swollen for several days. They gave us a preview of getting up quickly in the early morning, by blowing a bugle. You were to be outside in formation in 10 minutes. Your name was called and you answered Present And Accounted For. The Sergeant asked those in line who would be interested in Police Work to take one step forward. Quite a few...`,
      keywords: ["Fort MacArthur", "induction", "Los Angeles", "police work"]
    },
    {
      id: "page-002",
      legacyId: "IMG_0525",
      pageNumber: 2,
      file: "imgs/page-002-basic-training-camp-barkeley.jpeg",
      title: "Police Work and the Train to Texas",
      summary: "This scan finishes the 'police work' story, then moves into the train ride to Camp Barkeley and first impressions of the barracks.",
      transcription: `... thinking that would be a good thing to be in. The Sergeant then said all others line up for breakfast and the Police volunteers would Police the area. After they finished they could go to breakfast. It was a lesson not to volunteer if you didn't know what you were volunteering for. After about a week, we were loaded on a train to go to Basic Training. None of us recruits had any idea where we were headed. We went north for a while, then we went over the Sierra Nevada Mts. It was a beautiful ride. After a two-day ride we disembarked at Abilene, Texas. We were taken by trucks to a camp called, Camp Barkeley. As we arrived we looked at our nest homes. They were Tar Paper Barracks. The floors were planks and had cracks between the boards. We were told that these barracks were to be clean at all times.`,
      keywords: ["Camp Barkeley", "basic training", "Texas", "tar paper barracks"]
    },
    {
      id: "page-003",
      legacyId: "IMG_0526",
      pageNumber: 3,
      file: "imgs/page-003-live-fire-basic-training.jpeg",
      title: "Keeping the Barracks Clean",
      summary: "This scan stays with Camp Barkeley barracks life, inspections, and the daily battle against dust and sand.",
      transcription: `... Not knowing Texas weather, it didn't sound too hard to do. They showed us how the Army wanted us to keep our footlockers. Footlockers are where you keep your underwear, your socks, shaving gear, and all your personal effects. Your shoes were to shine like a new penny. The barracks were to be kept so clean that if the Captain inspected and in wiping with white gloves got them dirty, the whole Platoon would be restricted and no weekend passes would be issued. No one wanted to be guilty of restricting all. There was a lot of soap and water used for Q'ing (cleaning) the barracks. After cleaning, then you hoped that the wind wouldn't blow, as the sand would blow up through the cracks in the floor. The inspection would happen after breakfast. They have a saying in Texas, "if you don't like the weather wait 5 minutes and it will change," this was so true.`,
      keywords: ["live fire", "field training", "Camp Barkeley", "medical discharge"]
    },
    {
      id: "page-004",
      legacyId: "IMG_0527",
      pageNumber: 4,
      file: "imgs/page-004-medical-training-oreilly.jpeg",
      title: "Basic Training Under Live Fire",
      summary: "The basic-training section starts here and runs through the trench crawl under live ammunition.",
      transcription: `Basic Training lasted for 12 weeks. We had quite a lot of class work - learning map reading, compass training, Army etiquette (Yes Sir - No Sir), proper way to salute a superior, basic first aid, etc. We were assigned specific chores, working KP (Kitchen Patrol), Guard Duty. Also, we did daily marches with Galoshes. We made marches with full backpacks. We carried half a tent in our backpack and at night you pitched tent with another fellow, and you both have your tent halves. We also did night problems where you would be in a trench and you had to come out of the trench and creep and crawl across a field and they would fire live ammunition over the top of you. You learned soon how to keep down. It was a rainy night when we did this; the trench had about a foot of water in it, so it was real messy to creep and crawl. There was a young fellow who said He Couldn't Do This...`,
      keywords: ["O'Reilly General Hospital", "Springfield", "medical training", "bandaging"]
    },
    {
      id: "page-005",
      legacyId: "IMG_0528",
      pageNumber: 5,
      file: "imgs/page-005-camp-beale-camp-gruber.jpeg",
      title: "The Medical Decision",
      summary: "This scan finishes the trench incident and moves through the equivalency test, smoking habit, and choice of medical training.",
      transcription: `... He was told He Had To Do It so "get with it." Well, no sooner than he got out of the trench, he had an Epileptic Fit. They had to stop the guns and get a litter and carried him off the range. We never saw him again, so I guess he received a Medical Discharge. We had to take an Equivalency Test so they could reassign you to Officers Training or Medical Training at an Army Hospital. I scored 115 points and was given a choice of doing either training. I was getting a little Army smart and chose the medical training. While in basic training I took up smoking as each hour they would take a five-minute break and would say, "All light up that wants to." I thought why not join with everyone as they all seemed to enjoy the break. This bad habit lasted about 45 years and became so very hard to stop.`,
      keywords: ["Camp Beale", "Camp Gruber", "135th Evacuation Hospital", "reassignment"]
    },
    {
      id: "page-006",
      legacyId: "IMG_0529",
      pageNumber: 6,
      file: "imgs/page-006-unit-formation-blindfold-test.jpeg",
      title: "Training at O'Reilly General Hospital",
      summary: "The Springfield section begins here, covering classes, ward work, and the field-bandaging instruction he was asked to teach.",
      transcription: `Finally the day arrived and I was called to go to Springfield, MO, to O'Reilly General Hospital. We were assigned to nice white barracks there, so much nicer than the Tar Paper ones in Camp Barkeley. We were told that we would go to classes and also work in the Wards at the hospital. I did good in all the classes except Ceph in Materia Medica. This involved the use of mathematics, where you also had to know about grams, and also problems that needed a Chemistry background. I never took Chemistry in High school. I was exceptionally good at bandaging, and after the class graduated and was to be assigned as a Unit, I and another fellow didn't get assigned, as they wanted us to stay a little longer and I was to teach field bandaging. I can't remember what Paul Wiehe was to teach.`,
      keywords: ["Camp Gruber", "135th Evacuation Hospital", "blindfold", "bandaging"]
    },
    {
      id: "page-007",
      legacyId: "IMG_0530",
      pageNumber: 7,
      file: "imgs/page-007-motor-pool-transfer.jpeg",
      title: "Back to Barkeley, Then Camp Beale",
      summary: "The route turns west again: back to Barkeley, reunion with Sweeney, Camp Beale, and orders toward Camp Gruber.",
      transcription: `I stayed at O'Reilly another month and a half. Then I was sent back to Barkeley for reassignment. I was then reunited with a fellow from San Diego, his name was Sweeney. He had been a Pharmaceutical Salesman in civilian life. In Basic Training he had suffered a groin rupture and was just recovering as I returned to Barkeley. I was soon on another train headed West. I was on my way to Camp Beale in California. It was located near Marysville, CA. This was what they called a POC which meant you were going overseas. After a short time there, assignments were being made. They called 99 of us as a unit and instead of going overseas, we were to be sent back to Camp Gruber in Oklahoma to form a Field Evacuation Hospital. We again had to attend more classes and become a cohesive unit.`,
      keywords: ["Motor Pool", "Sergeant Garcia", "captain", "transfer"]
    },
    {
      id: "page-008",
      legacyId: "IMG_0531",
      pageNumber: 8,
      file: "imgs/page-008-convoy-departure-new-york.jpeg",
      title: "Forming the 135th Evacuation Hospital",
      summary: "The scan covers unit formation, the cadre tension, and the start of the blindfold bandaging confrontation.",
      transcription: `We became the 135th Evacuation Hospital. The Cadre in our unit was a bunch of Infantry rejects; they all had stripes on their uniforms. After all the training some of us had, there was no way to upgrade our ranks and earn more pay. The worst part was, they were to do all the teaching. I fell asleep in a class on bandaging, and the Sergeant had a fellow next to me wake me up. He said, "I suppose you know all about this subject." I said "Yes Sir, and could do that without a bandage, blindfolded." Without what, he had me come up front, blindfold me, and said "Go ahead." I did the bandage, and after class I ran to report him to the Captain's office. The First Sergeant wasn't...`,
      keywords: ["Fort Dix", "New York", "convoy", "Atlantic crossing"]
    },
    {
      id: "page-009",
      legacyId: "IMG_0532",
      pageNumber: 9,
      file: "imgs/page-009-convoy-collision-at-sea.jpeg",
      title: "Captain's Office and Motor Pool Transfer",
      summary: "The classroom dispute lands in the captain's office, ends in a motor-pool transfer, and starts the move east toward Fort Dix.",
      transcription: `... going to let me talk to the Captain, as he was a friend of the fellow teaching the class. Well, in the meantime the class instructor came in, and there was some loud exclamation made. The Captain came to the door to see what was happening. He told the First Sergeant to cool down, and he asked me to come into his office. I explained what happened and I told him I would like a transfer to another unit. He said he couldn't do that but I could transfer to the Motor Pool if I wanted, and I wouldn't have to attend any more classes. I readily agreed and I really liked Sergeant Garcia who ran the Motor Pool. He made me the Motor Pool Dispatcher. Soon after we were on the train and we found our destination...`,
      keywords: ["collision", "convoy", "fog", "hi-octane gasoline"]
    },
    {
      id: "page-010",
      legacyId: "IMG_0533",
      pageNumber: 10,
      file: "imgs/page-010-england-france-germany-advance.jpeg",
      title: "Fort Dix and the Convoy Departure",
      summary: "The unit reaches Fort Dix, boards in New York, and puts out into the Atlantic convoy, ending on the first sign of trouble at sea.",
      transcription: `... to be Fort Dix near New Brunswick, New Jersey. After a couple of days there we were taken to New York and boarded a ship headed for Europe. We didn't know it but we were in a 99-boat Convoy headed for France, finally going to the War Zone. We departed New York the 23rd of March. It was interesting looking either direction to see boats, all in a row, as far as you could see. Each day we practiced drills, in case there would be an emergency. We were to come to the deck for instructions. The ship was three decks deep in the vessel. Many people on the boat were sea sick. It was estimated by sick bay about 60% of personnel were up chucking. On about the 5th night around 10 pm I was laying on my bunk when there was a grinding sound.`,
      keywords: ["Southampton", "Camp Lucky Strike", "Aachen", "Cologne", "Hambourne"]
    },
    {
      id: "page-011",
      legacyId: "IMG_0534",
      pageNumber: 11,
      file: "imgs/page-011-hamborn-motor-pool-barters.jpeg",
      title: "Collision in the Fog",
      summary: "This scan captures the collision itself, the panic on deck, and the first realization of how close the convoy came to disaster.",
      transcription: `The boat kind of lurched. I thought like we had struck a sand bar and it was moving back and forth trying to dislodge itself. Then the emergency bells and lights came on and we were to go to the deck. Several fellows completely lost it. A big fellow from Oklahoma came running and flailing his arms. We ran over quite a few people and really messed up the evacuation drill. I and a fellow named Dean decided there was no way to try to get out, and that we would just wait and go out when things quieted down. What happened was not a torpedo, but the night was quite foggy, and the boat to our right mistook a blinker signal and turned, and came right in front of us. We hit them right in the middle of their boat.`,
      keywords: ["Hamborn", "motor pool", "occupation", "barter"]
    },
    {
      id: "page-012",
      legacyId: "IMG_0535",
      pageNumber: 12,
      file: "imgs/page-012-paris-supply-run.jpeg",
      title: "After the Collision: Southampton and France",
      summary: "The convoy incident gives way to repairs in Southampton, the Channel crossing, and arrival at Camp Lucky Strike.",
      transcription: `It hit them right in the Crew Quarters. We heard it killed seven of their crew. The scraping sound we heard was our boat trying to dislodge from them. Their cargo was Hi-Octane Gasoline. If we had hit them 10 ft either way we all would have been blown out of the water. The next morning the Captain said we did so good in the emergency drill that we wouldn't have to practice anymore. I figured the drill was a complete flop, and that we were so fortunate to be alive. Our ship was to go to Southampton, England, for repairs. We arrived in Southampton April 6 and was transferred to an English (Luny Boat) to go across the English Channel to France. We landed on the coast near Normandy Beach. We were assigned to Camp Lucky Strike, a Tent Camp, near Rouen, France. We never got our tents put up...`,
      keywords: ["Lt. Intrater", "Paris", "supply depots", "wine cellar"]
    },
    {
      id: "page-013",
      legacyId: "IMG_0536",
      pageNumber: 13,
      file: "imgs/page-013-lyon-eisenhower-jacket.jpeg",
      title: "France to Germany, Then Hambourne",
      summary: "The advance runs from France through Aachen and Cologne into the Ruhr, ending with the hospital setup at Hambourne.",
      transcription: `... then we were told to pack up, and that we were now in the Second Army and that we were going to catch up to Patton's Army on his drive through France and into Germany. We went through the Maginot Line and into Germany through Aachen. The City of Aachen was a completely bombed out place. I don't believe that a single building downtown had four outside walls standing. We hurried through as we were trying to catch Patton. We passed a number of villages with no sign of warfare. Finally we reached Cologne, only to see it completely devastated. At this point we received orders to go to a town called Hambourne and set up our Hospital there. We arrived there and took over their hospital and all of the houses adjacent to the hospital to house our troops. The Motor Pool took over a large garage...`,
      keywords: ["Lyon", "Eisenhower jacket", "Sergeant Golden", "supply depot"]
    },
    {
      id: "page-014",
      legacyId: "IMG_0537",
      pageNumber: 14,
      file: "imgs/page-014-marseille-redeployment.jpeg",
      title: "Occupation Duty and the Paris Supply Run",
      summary: "Occupation life in Hambourne blends into barter, motor-pool duty, and the start of the Paris supply run.",
      transcription: `... garage and had a lot of room for our vehicles. We all learned a few words in German. We would exchange food and candy bars for schnapps. Schnapps is a very fine white wine. We also were able to trade for things like cameras, binoculars, etc. While in Hambourne, the Supply Lieutenant, Lt. Intrater was going to make a trip to several Supply Depots. Being I was the Motor Pool Dispatcher, I chose to drive him. A Sergeant from the Supply room was to go along. Our first stop was in Paris. We visited a wine cellar under the street. The wine bottles were stored on shelves that could be rotated. It took years for the wine to complete the circle in the aging process. After touring the wine cellar we came up into a large foyer, and they had us sample the wine. It was a white or clear as water wine and was very good.`,
      keywords: ["Marseille", "R&R", "Pacific", "point system"]
    },
    {
      id: "page-015",
      legacyId: "IMG_0538",
      pageNumber: 15,
      file: "imgs/page-015-north-atlantic-storm.jpeg",
      title: "Lyon, Marseille, and Redeployment Orders",
      summary: "The Lyon trip closes and the Marseille redeployment sequence begins, with the Pacific still a looming possibility.",
      transcription: `... After leaving Paris we went South to Lyon, St. It was a beautiful city. We went to a supply depot several miles out in the country. Lt. Intrater got both a Sergeant Golden and myself an Eisenhower jacket. To make a long story short, we had a lot of fun and the trip took 11 days to go where the Lt. had business. When we got back to Hambourne, the War in Europe was coming to a close. Shortly after we were ordered to go to a Camp near Marseille. It was called an R & R Camp, and was in the desert. R & R really means Rest & Recuperation. I really think they wanted us close to a port so we could be sent to the Pacific Area. After several weeks we received orders to load on a ship going to the Orient for occupation duty.`,
      keywords: ["North Atlantic", "storm", "return voyage", "Mediterranean"]
    },
    {
      id: "page-016",
      legacyId: "IMG_0539",
      pageNumber: 16,
      file: "imgs/page-016-fort-dix-homecoming.jpeg",
      title: "Point System and the North Atlantic Storm",
      summary: "The end of the war in Europe, the point system, and the first part of the stormy return crossing share this scan.",
      transcription: `An Armistice brought the war in Europe to the end. Now the problem was to bring our servicemen home to be discharged. A point system was devised to send the men who had been in the European area the longest to be first to go home. It so happened that we had been first loaded in our boat, then it was decided to load the highest point men on our boat and to send this boat to the U.S.A. They decided to leave us as they didn't want to unload our equipment. We left France on the 17th of August and for some reason after leaving the Mediterranean we went north to cross the Atlantic by the North Atlantic route. We ran into a big storm and I just want to say I never believed waves could be so large. I'm sure that waves were 50 or more feet in height. We were...`,
      keywords: ["Fort Dix", "New York", "train", "Fort MacArthur"]
    },
    {
      id: "page-017",
      legacyId: "IMG_0540",
      pageNumber: 17,
      file: "imgs/page-017-discharge-fort-macarthur.jpeg",
      title: "Homecoming and Discharge",
      summary: "The last scan finishes the storm crossing, then covers New York, Fort Dix, Fort MacArthur, and the final discharge record.",
      transcription: `... tossed about like a leaf by those huge waves. We were told to stay below but, I just had to have a look. One look is all I wanted so I never forget that ocean. We arrived in New York on Aug. 27, 1945. Again we were sent to Fort Dix in New Jersey. We spent some time there and finally put on a train to go to California. Due to heavy rail traffic we spent 7 days crossing good old U.S.A. We arrived at Fort MacArthur Feb. 28, 1946. After a period of time I was discharged on March 31, 1946. My total service time was 2 years, 3 mos, and 28 days. I received 4 medals and a lot of valuable experience as a soldier.`,
      keywords: ["discharge", "Fort MacArthur", "medals", "service time"]
    }
  ],
  missions: [
    {
      id: 1,
      act: "training",
      title: "Induction and Basic Training",
      dateLabel: "October 1943 to early 1944",
      coords: [32.4487, -99.7331],
      zoom: 5,
      primaryDocId: "page-003",
      relatedDocIds: ["page-001", "page-002", "page-003"],
      excerpt: `We also did night problems where you would be in a trench and you had to come out of the trench and creep and crawl across a field and they would fire live ammunition over the top of you.`,
      narrative: "The manuscript opens with the sudden compression of Army life: induction, barracks discipline, then field training severe enough to strip away any illusion that service would stay abstract or ceremonial.",
      contextNote: "Camp Barkeley near Abilene was a major wartime training center. The Texas weather, temporary barracks, and live-fire exercises in the manuscript match the kind of accelerated preparation the Army used for wartime mobilization.",
      sourceLabel: "Source: Page 3, supported by Pages 1-3 (legacy IMG_0526; related IMG_0524-IMG_0526)",
      verificationNote: "Page 1 anchors the induction date at October 7, 1943, with reporting to Fort MacArthur on October 23, 1943."
    },
    {
      id: 2,
      act: "training",
      title: "Medical Training at O'Reilly",
      dateLabel: "1944",
      coords: [37.2089, -93.2923],
      zoom: 6,
      primaryDocId: "page-004",
      relatedDocIds: ["page-004"],
      excerpt: `I scored 115 points and was given a choice of doing either training. I was getting a little Army smart and chose the medical training.`,
      narrative: "Instead of officer training, he chooses the hospital path. That decision narrows the story from a generic Army journey into the lived rhythm of wards, classes, and field bandaging.",
      contextNote: "O'Reilly General Hospital in Springfield, Missouri, was a major Army medical installation and training site during the war, which fits the manuscript's account of formal medical instruction and ward work.",
      sourceLabel: "Source: Page 4 (legacy IMG_0527)",
      verificationNote: "The manuscript's course title 'Ceph in Materia Medica' is left as written; the exact classroom terminology may have been abbreviated in memory."
    },
    {
      id: 3,
      act: "training",
      title: "Across the Country to Form a Unit",
      dateLabel: "1944",
      coords: [39.1141, -121.3447],
      zoom: 5,
      primaryDocId: "page-005",
      relatedDocIds: ["page-005"],
      excerpt: `They called 99 of us as a unit and instead of going overseas, we were to be sent back to Camp Gruber in Oklahoma to form a Field Evacuation Hospital.`,
      narrative: "The route zigzags from Missouri to California and back to Oklahoma, emphasizing how little control individual soldiers had over the machinery moving them toward war.",
      contextNote: "The manuscript's use of 'POC' is preserved as written. The larger point is clear: Camp Beale briefly looked like the final staging ground before the unit was redirected to build the 135th Evacuation Hospital.",
      sourceLabel: "Source: Page 5 (legacy IMG_0528)",
      verificationNote: "Camp Beale was near Marysville, California, matching the place reference in the manuscript."
    },
    {
      id: 4,
      act: "training",
      title: "The Blindfold Challenge",
      dateLabel: "Late 1944",
      coords: [35.7126, -95.1766],
      zoom: 6,
      primaryDocId: "page-006",
      relatedDocIds: ["page-006", "page-007"],
      excerpt: `I said "Yes Sir, and could do that without a bandage, blindfolded."`,
      narrative: "What reads almost like a scene from a film is grounded in two consecutive pages: the quarrel in class, the bandaging demonstration, and the instinct to go straight to the captain.",
      contextNote: "By this point the 135th Evacuation Hospital is taking shape. The pages also explain why he leaves the medical classroom track and moves into the motor pool, a role that shapes the rest of the wartime route.",
      sourceLabel: "Source: Page 6, continued on Page 7 (legacy IMG_0529-IMG_0530)",
      verificationNote: "The quoted challenge appears on Page 6; the transfer outcome is documented on Page 7."
    },
    {
      id: 5,
      act: "crossing",
      title: "Deployment to Europe",
      dateLabel: "March 23, 1945",
      coords: [40.6023, -74.6168],
      zoom: 5,
      primaryDocId: "page-008",
      relatedDocIds: ["page-008"],
      excerpt: `We didn't know it but we were in a 99-boat Convoy headed for France, finally going to the War Zone.`,
      narrative: "After months of preparation, the story suddenly widens. Fort Dix, New York Harbor, and the line of ships on the horizon turn private recollection into a theater-scale movement.",
      contextNote: "Fort Dix was a major embarkation and demobilization hub. The convoy language and departure date place this crossing in the final weeks of the European war.",
      sourceLabel: "Source: Page 8 (legacy IMG_0531)",
      verificationNote: "The manuscript dates the departure from New York to March 23; the Southampton arrival on the next page is April 6."
    },
    {
      id: 6,
      act: "crossing",
      title: "Collision in the Fog",
      dateLabel: "Late March 1945",
      coords: [45.0, -30.0],
      zoom: 4,
      primaryDocId: "page-009",
      relatedDocIds: ["page-009"],
      excerpt: `Their cargo was Hi-Octane Gasoline. If we had hit them 10 ft either way we all would have been blown out of the water.`,
      narrative: "Before reaching combat duty, the journey almost ends in the Atlantic. The scene is vivid because it stays close to physical sensation: the grinding hull, the panic on deck, and the realization of how narrowly disaster was avoided.",
      contextNote: "Convoy operations reduced submarine risk but created their own dangers in darkness and fog. This page records one of the memoir's clearest near-death episodes.",
      sourceLabel: "Source: Page 9 (legacy IMG_0532)",
      verificationNote: "The number of dead crewmen and the gasoline cargo are presented as remembered testimony from the manuscript."
    },
    {
      id: 7,
      act: "europe",
      title: "Repairs in England",
      dateLabel: "April 6, 1945",
      coords: [50.9097, -1.4044],
      zoom: 6,
      primaryDocId: "page-010",
      relatedDocIds: ["page-010"],
      excerpt: `We arrived in Southampton April 6 and was transferred to an English (Luny Boat) to go across the English Channel to France.`,
      narrative: "England appears only briefly, almost as an intermission forced by damaged steel. Then the manuscript moves immediately back into motion, across the Channel and toward France.",
      contextNote: "The page ties the convoy collision directly to repairs at Southampton. The manuscript term 'Luny Boat' is retained verbatim because the exact vessel type is unclear.",
      sourceLabel: "Source: Page 10 (legacy IMG_0533)",
      verificationNote: "This mission intentionally shares Page 10 with the next three stages because the manuscript compresses the advance into one dense page."
    },
    {
      id: 8,
      act: "europe",
      title: "Camp Lucky Strike",
      dateLabel: "April 1945",
      coords: [49.8000, 0.7000],
      zoom: 7,
      primaryDocId: "page-010",
      relatedDocIds: ["page-010"],
      excerpt: `We were assigned to Camp Lucky Strike, a Tent Camp, near Rouen, France. We never got our tents put up then we were told to pack up.`,
      narrative: "The stop in France is fleeting. The camp exists in the story less as a place to inhabit than as a signal that the front is moving so fast the unit barely pauses before heading east.",
      contextNote: "Camp Lucky Strike was one of the major cigarette camps in northern France used for staging and transit. The manuscript places it 'near Rouen'; modern histories place it closer to Saint-Valery-en-Caux and the Le Havre staging area.",
      sourceLabel: "Source: Page 10 (legacy IMG_0533)",
      verificationNote: "The place description is clarified in the note, but the quoted wording remains exactly as written in the manuscript."
    },
    {
      id: 9,
      act: "europe",
      title: "Through Aachen and Cologne",
      dateLabel: "Spring 1945",
      coords: [50.7753, 6.0839],
      zoom: 7,
      primaryDocId: "page-010",
      relatedDocIds: ["page-010"],
      excerpt: `The City of Aachen was a completely bombed out place. I don't believe that a single building downtown had four outside walls standing.`,
      narrative: "Here the memoir widens into the devastated landscape of western Germany. After the suspense of the crossing, the ruined cities deliver the clearest visual evidence of the war's scale.",
      contextNote: "Aachen and Cologne had both suffered severe wartime destruction. The manuscript also says the unit was in the 'Second Army' while hurrying to catch Patton's army; that command relationship is left unresolved here rather than overstated.",
      sourceLabel: "Source: Page 10 (legacy IMG_0533)",
      verificationNote: "This mission and the previous two all reference Page 10 because the original page covers the move from England into Germany in one continuous account."
    },
    {
      id: 10,
      act: "europe",
      title: "Hospital Duty in Hamborn",
      dateLabel: "Spring to Summer 1945",
      coords: [51.4900, 6.7500],
      zoom: 8,
      primaryDocId: "page-011",
      relatedDocIds: ["page-010", "page-011"],
      excerpt: `We would exchange food and candy bars for schnapps. Schnapps is a very fine white wine.`,
      narrative: "Once the unit stops moving, the tone changes. The story shifts from ruined cities and orders to the uneasy routines of occupation: commandeered buildings, a functioning motor pool, and barter in a half-broken local economy.",
      contextNote: "The manuscript spells the town 'Hambourne.' The most likely modern identification is Hamborn, now part of Duisburg in the Ruhr.",
      sourceLabel: "Source: Page 11, with arrival established on Page 10 (legacy IMG_0534; related IMG_0533)",
      verificationNote: "The 'schnapps' description is preserved as written even though the exact drink type is not independently verified."
    },
    {
      id: 11,
      act: "europe",
      title: "Supply Run to Paris",
      dateLabel: "1945",
      coords: [48.8566, 2.3522],
      zoom: 6,
      primaryDocId: "page-012",
      relatedDocIds: ["page-012"],
      excerpt: `Our first stop was in Paris. We visited a wine cellar under the street.`,
      narrative: "The supply trip briefly breaks the wartime rhythm. Paris enters the memoir not as a grand historical tableau but as a practical stop that happens to offer wine, distance from the front, and a glimpse of another Europe.",
      contextNote: "Because he was the motor pool dispatcher, driving Lt. Intrater put him in a role that offered mobility, trust, and unusual access compared with routine hospital duty.",
      sourceLabel: "Source: Page 12 (legacy IMG_0535)",
      verificationNote: "This scene is grounded entirely in the manuscript and not expanded beyond what the page supports."
    },
    {
      id: 12,
      act: "europe",
      title: "Down to Lyon",
      dateLabel: "1945",
      coords: [45.7640, 4.8357],
      zoom: 6,
      primaryDocId: "page-013",
      relatedDocIds: ["page-013"],
      excerpt: `Lt. Intrater got both a Sergeant Golden and myself an Eisenhower jacket.`,
      narrative: "The detour continues south. In a memoir full of barracks, trucks, and ruined cities, the jacket stands out as a small, vivid token of comfort and status.",
      contextNote: "The short waist-length Eisenhower jacket was common late in the war and often prized by enlisted men. The page frames the trip as both official business and a rare stretch of relative ease.",
      sourceLabel: "Source: Page 13 (legacy IMG_0536)",
      verificationNote: "The manuscript's place reference 'Lyon, St.' is preserved in the transcription and normalized to Lyon in the mission title."
    },
    {
      id: 13,
      act: "return",
      title: "Marseille and the End of the War in Europe",
      dateLabel: "Summer 1945",
      coords: [43.2965, 5.3698],
      zoom: 7,
      primaryDocId: "page-014",
      relatedDocIds: ["page-014"],
      excerpt: `I really think they wanted us close to a port so we could be sent to the Pacific Area.`,
      narrative: "Victory in Europe does not feel restful in the memoir. Even the so-called R and R camp is shadowed by the possibility of redeployment to another war.",
      contextNote: "Southern France, including the Marseille area, became a major staging zone for redeployment and return shipping as the European war closed.",
      sourceLabel: "Source: Page 14 (legacy IMG_0537)",
      verificationNote: "The manuscript uses 'Armistice' to describe the end of the war in Europe; the page is presented as personal recollection rather than formal diplomatic terminology."
    },
    {
      id: 14,
      act: "return",
      title: "North Atlantic Return",
      dateLabel: "August 1945",
      coords: [42.0, -40.0],
      zoom: 4,
      primaryDocId: "page-015",
      relatedDocIds: ["page-015"],
      excerpt: `We were tossed about like a leaf by those huge waves.`,
      narrative: "The return voyage is not triumphant. Instead it becomes another ordeal, with the sea itself serving as the final force the unit must survive before the United States comes back into view.",
      contextNote: "The memoir describes leaving France on August 17 and then taking a northern Atlantic route after passing out of the Mediterranean. The route detail is preserved as remembered testimony.",
      sourceLabel: "Source: Page 15 (legacy IMG_0538)",
      verificationNote: "The estimate of fifty-foot waves is kept as the author's lived impression rather than recast as a measured report."
    },
    {
      id: 15,
      act: "return",
      title: "Fort Dix to Fort MacArthur",
      dateLabel: "August 27, 1945 to February 28, 1946",
      coords: [40.6023, -74.6168],
      zoom: 5,
      primaryDocId: "page-016",
      relatedDocIds: ["page-016"],
      excerpt: `Due to heavy rail traffic we spent 7 days crossing good old U.S.A.`,
      narrative: "Homecoming arrives in pieces: New York first, then Fort Dix again, then a slow rail crossing that makes the continent feel as vast on the return as it did on the way out.",
      contextNote: "Fort Dix served both outbound and returning troop traffic, which matches the manuscript's use of it as a repeated waypoint.",
      sourceLabel: "Source: Page 16 (legacy IMG_0539)",
      verificationNote: "The manuscript gives the return to Fort MacArthur as February 28, 1946, months after the August 1945 arrival in New York."
    },
    {
      id: 16,
      act: "return",
      title: "Discharge",
      dateLabel: "March 31, 1946",
      coords: [33.7139, -118.2937],
      zoom: 8,
      primaryDocId: "page-017",
      relatedDocIds: ["page-017"],
      excerpt: `My total service time was 2 years, 3 mos, and 28 days.`,
      narrative: "The final page is brief and plainspoken. After the long route mapped across the site, the closing emphasis is not on spectacle but on elapsed time, medals, and experience carried forward.",
      contextNote: "The memoir closes where it began, at Fort MacArthur in California, turning the full route into a circle rather than a straight line home.",
      sourceLabel: "Source: Page 17 (legacy IMG_0540)",
      verificationNote: "The manuscript states that he received four medals; the service record panel in the site should match that total."
    }
  ],
  serviceMilestones: [
    { id: "field-medic", name: "Field Medic", icon: "Cross", desc: "Completed medical training at O'Reilly General Hospital.", missionId: 2 },
    { id: "atlantic-crossing", name: "Atlantic Crossing", icon: "Convoy", desc: "Sailed for Europe with the convoy from New York.", missionId: 5 },
    { id: "occupation-duty", name: "Occupation Duty", icon: "Hospital", desc: "Served with the unit after the advance into Germany.", missionId: 10 },
    { id: "honorable-discharge", name: "Honorable Discharge", icon: "Record", desc: "Returned home and completed service at Fort MacArthur.", missionId: 16 }
  ]
};
